### ISSUE TITLE
Drop guzzle dependency and depend on the one from server

### ISSUE THREAD

**Issue by rullzer** [NastuzziSamy/files_external_gdrive#27]
Currently guzzle is added here. But this is a different version than NC14 ships itself.
Doing :boom: basically if you try to run with this app enabled.

**Comment by StygianBlues** [comment]
+1

**Comment by Ra72xx** [comment]
Please fix this! This causes lots of strange problems during nextcloud upgrades, breaks compatibility e.g. with bookmarks app etc.
+1

**Comment by nonplusnl** [comment]
This completely broke my Nextcloud upgrade (from 13 to 14). It took me a while to find out what caused the problem, as the update got stuck while checking for app updates in the appstore (in other words, at a point where no link to this app is obvious). While I think the Nextcloud upgrade process should not crash so badly due to an external app, it would certainly help to fix this issue/enhancement. Thanks!

**Comment by NastuzziSamy** [comment]
I had the same, I am sorry, the app is in beta and as it is not stable, a lot of problems come up. 

Just for others, you need to disable the app before upgrading or you will be unable to to do anything

**Comment by wioxjk** [comment]
Caused alot of headache because of this, pls fix :)

**Comment by bmaehr** [comment]
Please mark as not compatible with nextcloud 14!

**Comment by knut-hildebrandt** [comment]
Same here, Update from NC 13.0.8 to 14.0.4 was a nightmare. Only worked when the app was disabled. After re-enabling it the server showed strange behavior and constantly showed the "Internal Server Error" page.

**Comment by malien24** [comment]
It incompatible with news app thru guzzle

**Comment by NastuzziSamy** [comment]
Hey guys, it is fixed in the last commit, thx :)
